# Generated by Django 3.2.19 on 2023-05-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptationResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('direction', models.CharField(max_length=5)),
                ('source_id', models.CharField(max_length=10)),
                ('adapted_title', models.CharField(max_length=50, null=True)),
                ('adapted_ingredients', models.CharField(max_length=255, null=True)),
                ('adapted_steps', models.CharField(max_length=512, null=True)),
                ('comment', models.CharField(max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('direction', models.CharField(max_length=5)),
                ('source_id', models.CharField(max_length=10)),
                ('generated_recipe', models.CharField(max_length=600)),
                ('method', models.CharField(max_length=20)),
                ('grammar_score', models.PositiveSmallIntegerField(null=True)),
                ('correct_score', models.PositiveSmallIntegerField(null=True)),
                ('preservation_score', models.PositiveSmallIntegerField(null=True)),
                ('cultural_align_score', models.PositiveSmallIntegerField(null=True)),
                ('comment', models.CharField(max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeAdaptation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('direction', models.CharField(max_length=5)),
                ('source_id', models.CharField(max_length=10)),
                ('source_title', models.CharField(max_length=50, null=True)),
                ('source_title_translated', models.CharField(max_length=50, null=True)),
                ('source_ingredients', models.CharField(max_length=255)),
                ('source_steps', models.CharField(max_length=512)),
                ('source_dish', models.CharField(max_length=50, null=True)),
                ('source_index', models.IntegerField()),
                ('ref_id', models.CharField(max_length=10)),
                ('ref_title', models.CharField(max_length=50, null=True)),
                ('ref_title_translated', models.CharField(max_length=50, null=True)),
                ('ref_ingredients', models.CharField(max_length=255)),
                ('ref_steps', models.CharField(max_length=512)),
                ('ref_dish', models.CharField(max_length=50, null=True)),
                ('labeled_times', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('direction', models.CharField(max_length=255)),
                ('source_id', models.CharField(max_length=255)),
                ('source_title', models.CharField(max_length=255, null=True)),
                ('source_title_translated', models.CharField(max_length=255, null=True)),
                ('source_ingredients', models.CharField(max_length=255, null=True)),
                ('source_steps', models.CharField(max_length=255, null=True)),
                ('source_dish', models.CharField(max_length=255, null=True)),
                ('source_index', models.CharField(max_length=255, null=True)),
                ('generated_recipe', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_email', models.CharField(max_length=255)),
            ],
        ),
    ]
