# Generated by Django 3.2.19 on 2023-05-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaptationresults',
            name='test_cy',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
