# Generated by Django 3.2.19 on 2023-05-21 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_adaptationresults_test_cy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adaptationresults',
            name='test_cy',
        ),
    ]
