# Generated by Django 3.2.19 on 2023-05-21 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20230521_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adaptationresults',
            old_name='user_id',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='evaluationresults',
            old_name='user_id',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='recipeadaptation',
            old_name='user_id',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='recipeevaluation',
            old_name='user_id',
            new_name='user_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
