# Generated by Django 3.2.19 on 2023-05-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20230522_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationresults',
            name='generated_recipe',
            field=models.CharField(max_length=3096),
        ),
        migrations.AlterField(
            model_name='recipeadaptation',
            name='ref_steps',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='recipeadaptation',
            name='source_steps',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='recipeevaluation',
            name='generated_recipe',
            field=models.CharField(max_length=3096),
        ),
        migrations.AlterField(
            model_name='recipeevaluation',
            name='source_steps',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
