# Generated by Django 3.2.19 on 2023-05-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20230522_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaptationresults',
            name='adapted_ingredients',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='adaptationresults',
            name='adapted_steps',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='adaptationresults',
            name='comment',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
