# Generated by Django 3.2.19 on 2023-05-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20230522_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeevaluation',
            old_name='source_dish',
            new_name='ref_title',
        ),
        migrations.RemoveField(
            model_name='recipeevaluation',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='recipeevaluation',
            name='source_index',
        ),
        migrations.RemoveField(
            model_name='recipeevaluation',
            name='source_title_translated',
        ),
        migrations.AddField(
            model_name='recipeevaluation',
            name='ref_ingredients',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='recipeevaluation',
            name='ref_steps',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
