# Generated by Django 3.2.19 on 2023-05-23 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20230523_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeevaluation',
            old_name='method',
            new_name='methods',
        ),
    ]
