# Generated by Django 3.2.19 on 2023-05-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_method_recipeevaluation_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeevaluation',
            name='evaluted_times',
            field=models.IntegerField(default=0),
        ),
    ]
