# Generated by Django 3.2.19 on 2023-05-23 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_recipeevaluation_evaluted_times'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeevaluation',
            old_name='evaluted_times',
            new_name='evaluated_times',
        ),
    ]
