# Generated by Django 3.2.19 on 2023-05-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_evaluted_times_recipeevaluation_evaluated_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationresults',
            name='source_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
