# Generated by Django 3.2.19 on 2023-05-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_evaluationresults_source_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeadaptation',
            name='source_ingredients_translated',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipeadaptation',
            name='source_steps_translated',
            field=models.CharField(default='-', max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipeevaluation',
            name='source_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
