# Generated by Django 3.2.19 on 2023-05-26 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20230526_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationresults',
            name='source_title',
        ),
    ]
