# Generated by Django 3.2.19 on 2023-05-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_evaluationresults_source_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeevaluation',
            name='ref_ingredients',
        ),
        migrations.RemoveField(
            model_name='recipeevaluation',
            name='ref_steps',
        ),
        migrations.RemoveField(
            model_name='recipeevaluation',
            name='ref_title',
        ),
        migrations.AddField(
            model_name='recipeevaluation',
            name='ref_recipe',
            field=models.CharField(max_length=3096, null=True),
        ),
    ]
