# Generated by Django 3.2.19 on 2023-05-30 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20230526_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationresults',
            name='evaluation_time',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='evaluationresults',
            name='submission_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
