# Generated by Django 3.2.19 on 2023-05-30 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_evaluationresults_evaluation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaptationresults',
            name='adaptation_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='adaptationresults',
            name='submission_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
