# Generated by Django 3.2.19 on 2024-01-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_comprehensioncheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPT4ComprehensionCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=255)),
                ('submit_time', models.IntegerField(default=0)),
                ('correct', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GPT4EvaluationResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=255)),
                ('image_id', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=10)),
                ('s1', models.PositiveSmallIntegerField(null=True)),
                ('s2', models.PositiveSmallIntegerField(null=True)),
                ('s3', models.PositiveSmallIntegerField(null=True)),
                ('s4', models.PositiveSmallIntegerField(null=True)),
                ('s5', models.PositiveSmallIntegerField(null=True)),
                ('evaluation_time', models.IntegerField(null=True)),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GPT4EvaluationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=10)),
                ('left_img', models.CharField(max_length=512)),
                ('right_img', models.CharField(max_length=512)),
                ('golden', models.CharField(max_length=512)),
                ('gpt4_ret', models.CharField(max_length=512)),
                ('evaluated_times', models.IntegerField(default=0)),
            ],
        ),
    ]
