# Generated by Django 3.2.19 on 2024-02-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_gpt4comprehensioncheck_gpt4evaluationresults_gpt4evaluationsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllMaRVLData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.CharField(max_length=256)),
                ('img_name', models.CharField(max_length=64)),
                ('language', models.CharField(max_length=10)),
                ('evaluated_times', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FilterMaRVLResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=255)),
                ('img_path_label_1', models.CharField(max_length=256)),
                ('img_path_label_2', models.CharField(max_length=256)),
                ('img_path_label_3', models.CharField(max_length=256)),
                ('img_path_label_4', models.CharField(max_length=256)),
                ('img_path_label_5', models.CharField(max_length=256)),
                ('language', models.CharField(max_length=10)),
                ('evaluation_time', models.IntegerField(null=True)),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='gpt4evaluationresults',
            name='s1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gpt4evaluationresults',
            name='s2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gpt4evaluationresults',
            name='s3',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gpt4evaluationresults',
            name='s4',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='gpt4evaluationresults',
            name='s5',
            field=models.IntegerField(null=True),
        ),
    ]
